//
// You received this file as part of Finroc
// A framework for intelligent robot control
//
// Copyright (C) Finroc GbR (finroc.org)
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
//----------------------------------------------------------------------
package org.finroc.tools.finstruct.util;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.MouseEvent;

/**
 * @author Max Reichardt
 *
 * Handles mouse events in particular area of the screen
 */
public interface MouseHandler {

    /**
     * Does mouse handler handle this point?
     *
     * @param p Point
     * @return Answer
     */
    public boolean handlesPoint(Point p);

    /**
     * @return Mouse cursor for area in which handler is active - null for default cursor
     */
    public Cursor getCursor();

    /**
     * Called whenever mouse-over (=selection?) or activation status changed
     */
    public void statusChanged();

    /**
     * Called after mouse button was released
     *
     * @param event Mouse event (as generated by Swing)
     * @param over Handler that cursor was over while releasing
     */
    public void mouseReleased(MouseEvent event, MouseHandler over);
}
